[all]
cp-a      ansible_host=10.20.10.10 ip=10.20.10.10
cp-c      ansible_host=10.20.11.10 ip=10.20.11.10
cp-d      ansible_host=10.20.12.10 ip=10.20.12.10
etcd-a    ansible_host=10.20.20.10 ip=10.20.20.10
etcd-c    ansible_host=10.20.21.10 ip=10.20.21.10
etcd-d    ansible_host=10.20.22.10 ip=10.20.22.10
worker-a  ansible_host=10.20.10.20 ip=10.20.10.20
worker-c  ansible_host=10.20.11.20 ip=10.20.11.20
worker-d  ansible_host=10.20.12.20 ip=10.20.12.20

[kube_control_plane]
cp-a
cp-c
cp-d

[etcd]
etcd-a
etcd-c
etcd-d

[kube_node]
worker-a
worker-c
worker-d

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
